"""hee view --jobs --md: the whole SCORECARD.md is generated, in reading order.

Real trigger, 2026-09-11: after the Nodes rollup landed, the markdown printed
the agent table's header, then the whole Nodes table, then the agent rows, so
both tables rendered wrong. The title had been hand-added to every committed
copy, and the OK status line landed in the file."""
import subprocess, sys, unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VIEW = ROOT / "tooling" / "bin" / "hee-view"


class ScorecardMarkdown(unittest.TestCase):
    def test_title_order_and_no_status_in_the_file(self):
        r = subprocess.run([sys.executable, str(VIEW), "--jobs", "--md", "--root", "tests/fixtures/dispatch"],
                           cwd=ROOT, capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stderr)
        md = r.stdout
        self.assertTrue(md.startswith("# Agent scorecard\n"), md[:80])
        self.assertNotIn("hee-view:", md)
        self.assertNotIn("Generated by `hee view --jobs --md` from 0", md)
        lines = md.splitlines()
        agent_head = next(i for i, l in enumerate(lines) if l.startswith("| agent | jobs |"))
        node_head = next(i for i, l in enumerate(lines) if l.startswith("| node | role |"))
        self.assertLess(agent_head, node_head)
        between = [l for l in lines[agent_head + 2:node_head] if l.startswith("| ")]
        self.assertTrue(between, "agent rows must sit directly under the agent header")
        self.assertTrue(all(not l.startswith("| node") for l in between))
        self.assertTrue(all(l.startswith("| ") for l in lines[node_head + 2:] if l.strip()), "nothing but node rows after the node header")

    def test_same_records_same_file(self):
        run = lambda: subprocess.run([sys.executable, str(VIEW), "--jobs", "--md", "--root", "tests/fixtures/dispatch"],
                                     cwd=ROOT, capture_output=True, text=True).stdout
        self.assertEqual(run(), run())


if __name__ == "__main__":
    unittest.main()
