#!/usr/bin/env python3
"""Build a single, current index of every "# Thesis" / "## Follow-up" doc
under a docs tree, so scattered thesis debates are one browsable list
instead of dozens of raw files someone has to know to go find.

Same absorption-by-tool philosophy as tools/hee-pill-index.py (per
human-execution-engine#225) -- read-only against the source docs, never
rewrites them, only regenerates the generated index.

Per Spencer, 2026-08-18: "start collecting thesis debates" -- the docs
convention is `# Thesis` as the top heading, optionally followed by a
`## Follow-up` section. As of this tool's first run, no such docs exist
on `main` yet (they're real, but only in unmerged
human-execution-engine#218/#220 -- dedup between those two is a separate,
not-yet-done task, tracked on fleet-ops#173). This tool works against
whatever docs tree it's pointed at, so it's equally useful for a
dry-run preview against an unmerged branch and for the real index once
something actually lands on main.

Usage:
    python3 tools/hee-thesis-index.py [--root DIR] [--write] [--out PATH]

Without --write, prints the index to stdout (dry run). With --write,
writes to --out (default docs/THESIS_INDEX.md).
"""
from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_ROOT = REPO_ROOT / "hee" / "docs"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "THESIS_INDEX.md"

THESIS_HEADING_RE = re.compile(r"^#\s+Thesis\s*$", re.IGNORECASE)
FOLLOWUP_HEADING_RE = re.compile(r"^##\s+Follow-up\s*$", re.IGNORECASE)
ANY_HEADING_RE = re.compile(r"^#{1,6}\s")


class ThesisDoc:
    def __init__(self, path: pathlib.Path, thesis: str, followup: str | None):
        self.path = path
        self.thesis = thesis
        self.followup = followup

    def title(self) -> str:
        # Filenames in this convention are the real title (e.g.
        # "rms-lisp-to-replace-yaml.md") -- no separate title field exists
        # in the doc body, the heading is always literally "# Thesis".
        return self.path.stem.replace("-", " ")


def parse_thesis_doc(path: pathlib.Path) -> ThesisDoc | None:
    """Returns None if this file isn't actually a Thesis doc (no '# Thesis'
    heading) -- never fabricates a Thesis section that isn't really there."""
    raw_text = path.read_text(errors="replace")
    lines = raw_text.splitlines()

    thesis_start = None
    for i, line in enumerate(lines):
        if THESIS_HEADING_RE.match(line.strip()):
            thesis_start = i + 1
            break
    if thesis_start is None:
        return None

    thesis_lines: list[str] = []
    followup_lines: list[str] = []
    in_followup = False
    for line in lines[thesis_start:]:
        stripped = line.strip()
        if FOLLOWUP_HEADING_RE.match(stripped):
            in_followup = True
            continue
        if in_followup:
            if ANY_HEADING_RE.match(stripped) and not FOLLOWUP_HEADING_RE.match(stripped):
                break  # a further heading ends the Follow-up section
            followup_lines.append(line)
        else:
            if ANY_HEADING_RE.match(stripped) and not THESIS_HEADING_RE.match(stripped):
                break  # a heading other than Follow-up ends the Thesis section
            thesis_lines.append(line)

    thesis_text = "\n".join(thesis_lines).strip()
    followup_text = "\n".join(followup_lines).strip() or None
    if not thesis_text:
        return None
    return ThesisDoc(path, thesis_text, followup_text)


def collect_thesis_docs(root: pathlib.Path) -> list[ThesisDoc]:
    docs = []
    if not root.exists():
        return docs
    for path in sorted(root.rglob("*.md")):
        if path.is_file():
            doc = parse_thesis_doc(path)
            if doc:
                docs.append(doc)
    docs.sort(key=lambda d: str(d.path))
    return docs


def render_index(docs: list[ThesisDoc], root: pathlib.Path) -> str:
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        root_display = root.relative_to(REPO_ROOT)
    except ValueError:
        root_display = root
    lines = [
        "# Thesis Index (generated)",
        "",
        f"Regenerated: {now}",
        f"Scanned root: `{root_display}`",
        "",
        "Auto-generated by `tools/hee-thesis-index.py` -- do not hand-edit, "
        "re-run the script instead. Source docs are untouched by this tool; "
        "this is a read-only index over `# Thesis` / `## Follow-up` docs, "
        "same absorption-by-tool pattern as `docs/history/PILL_INDEX.md` "
        "(human-execution-engine#225).",
        "",
        f"{len(docs)} thesis doc(s) indexed.",
        "",
    ]
    if not docs:
        lines.append(
            "_None found under this root yet. Real thesis docs exist in "
            "unmerged human-execution-engine#218/#220 -- dedup between them "
            "is tracked separately (fleet-ops#173) and not resolved by this "
            "tool. Re-run once something real lands on `main`._"
        )
        lines.append("")
    for doc in docs:
        rel = doc.path.relative_to(REPO_ROOT) if REPO_ROOT in doc.path.parents else doc.path
        lines.append(f"## {doc.title()}")
        lines.append("")
        lines.append(f"`{rel}`")
        lines.append("")
        lines.append("**Thesis**")
        lines.append("")
        lines.append(doc.thesis)
        lines.append("")
        if doc.followup:
            lines.append("**Follow-up**")
            lines.append("")
            lines.append(doc.followup)
            lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=pathlib.Path, default=DEFAULT_ROOT, help="docs tree to scan (default: hee/docs/)")
    parser.add_argument("--write", action="store_true", help="write --out instead of printing")
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUTPUT, help="output path when --write is set")
    args = parser.parse_args()

    docs = collect_thesis_docs(args.root)
    output = render_index(docs, args.root)

    if args.write:
        args.out.write_text(output)
        print(f"Wrote {args.out} ({len(docs)} thesis docs)", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
