name: hee-preflight
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  hee-preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main # explicity main checkout
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep
      - name: HEE preflight
        run: ci/git/hee-preflight.sh --ci
